apiVersion: apps/v1
kind: Deployment
metadata:
 name: vhg-deployment
spec:
 replicas: 3
 selector:
   matchLabels:
     app: vhg
 template:
   metadata:
     labels:
       app: vhg
   spec:
     containers:
     - name: vhg
       image: beldenschroeder/vhg
       resources:
          limits:
            memory: 128Mi
            cpu: 500m
       ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vhg-svc
spec:
  selector:
    app: vhg
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000