apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: vhg
build:
  artifacts:
  # - image: lukondefmwila/express-test
  - image: beldenschroeder/vhg
    context: ./dist/apps/vhg
    docker:
      dockerfile: ./apps/vhg/Dockerfile
# test:
#   - context: .
#     # image: lukondefmwila/express-test
#     image: beldenschroeder/vhg
#     custom:
#       - command: npm run test
deploy:
  kubectl:
    manifests:
    - manifests.yaml
