apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: vhg
build:
  artifacts:
  - image: beldenschroeder/vhg
    docker:
      dockerfile: ./apps/vhg/Dockerfile
# TODO: Add a test step
# test:
#   - context: .
#     image: beldenschroeder/vhg
#     custom:
#       - command: npm run test
deploy:
  kubectl:
    manifests:
    - manifests.yaml
