apiVersion: apps/v1
kind: Deployment
metadata:
  name: vhg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: vhg
          image: beldenschroeder/vhg
          ports:
            - containerPort: 3000
