name: 'Build & Deploy to Production'
on:
  push:
    branches:
      - main
env:
  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:  
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1
        - name: Create ECR repository if it does not exist
          uses: int128/create-ecr-repository-action@v1
          with:
            repository: ${{ env.ECR_REPOSITORY }}
        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            IMAGE_TAG: v1
          run: |
            docker build --build-arg NODE_ENV=production --build-arg NEXT_PUBLIC_VERCEL_ENV=production --build-arg NEXT_PUBLIC_VERCEL_URL=vhgapp.beldenschroeder.me --build-arg DB_NAME=vonherffgallery --build-arg DB_CONN_STRING=mongodb://host.docker.internal:27017/${DB_NAME} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.prod .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
